doctrine:
    dbal:
        dbname:               rallysdb
        host:                 localhost
        port:                 3306
        user:                 root
        password:             Dubai007
        driver:               mysql
        # if the url option is specified, it will override the above config
        url:                  mysql://root:Dubai007@127.0.0.1:3306/rallysdb

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
