# Generated by Django 3.2.8 on 2021-11-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rallye',
            name='titre',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='question',
            name='nb_points',
            field=models.IntegerField(verbose_name='Nombre Points'),
        ),
        migrations.AlterField(
            model_name='rallye',
            name='presentation',
            field=models.TextField(default=None, null=True, verbose_name='Presentation'),
        ),
    ]
