# Generated by Django 3.1.5 on 2021-10-25 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_user', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Id user')),
                ('gender', models.CharField(default=None, max_length=1, null=True, verbose_name='Gender')),
                ('birth_date', models.DateField(default=None, null=True, verbose_name='Birth date')),
                ('pseudo', models.CharField(default=None, max_length=60, null=True, verbose_name='Pseudo')),
                ('region', models.CharField(default=None, max_length=255, null=True, verbose_name='Region')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('token', models.CharField(default=None, max_length=255, null=True, unique=True, verbose_name='Token')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Rallye',
            fields=[
                ('id_rallye', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Id Rallye')),
                ('adresse', models.CharField(default=None, max_length=255, null=True, verbose_name='Adresse')),
                ('presentation', models.CharField(default=None, max_length=255, null=True, verbose_name='Presentation')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rallyes',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id_question', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Id Question')),
                ('rang', models.IntegerField(verbose_name='Rang')),
                ('photo', models.CharField(default=None, max_length=255, null=True, verbose_name='Photo')),
                ('photo_style', models.CharField(default=None, max_length=255, null=True, verbose_name='Photo style')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('id_reponse', models.IntegerField(verbose_name='Id Reponse')),
                ('reponse', models.CharField(max_length=255, verbose_name='Reponse')),
                ('nb_points', models.IntegerField(verbose_name='Id Reponse')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('rallye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Questions', to='api.rallye')),
            ],
            options={
                'db_table': 'questions',
                'unique_together': {('rallye', 'rang')},
            },
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id_proposition', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Id Proposition')),
                ('proposition', models.CharField(max_length=255, verbose_name='Proposition')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Propositions', to='api.question')),
            ],
            options={
                'db_table': 'propositions',
            },
        ),
    ]
